version: "3.8"

services:
  wellspring:
    image: mysql:8.0
    container_name: wellspring_container
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "${FORWARD_DB_PORT}:3306"
    volumes:
      - wellspring:/var/lib/mysql
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD","mysqladmin", "ping", "-h","localhost", "-u","root","-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s

  wellspring_app:
    container_name: wellspring_app
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?charset=utf8mb4


    volumes:
      - ./:/app
    depends_on:
      wellspring:
        condition: service_healthy
    restart: unless-stopped

volumes:
  wellspring:
